import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "components/styles/Home.module.css";

import ResponsiveAppBar from 'src/component/header.js';
import Card from "src/component/card.js";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useAuthContext } from "components/context/state";



const inter = Inter({ subsets: ["latin"] });



export default function Home() {
  const router = useRouter();
  const { isAuth } = useAuthContext();
  useEffect(() => {
    if (!isAuth) {
      router.push("/signin")
    }
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main className={styles.main}>
      <ResponsiveAppBar></ResponsiveAppBar>
        
          
      <Card></Card>

          
      </main>
    </>
  );
}