import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from 'components/styles/Home.module.css'

import { useForm } from "react-hook-form";
import saveData from "./some_other_file";


const inter = Inter({ subsets: ['latin'] })

export default function Form() {
  const { register, handleSubmit } = useForm();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <ResponsiveAppBar></ResponsiveAppBar> 

      <form onSubmit={handleSubmit(data => saveData(data))}>
        <h1>New Order</h1>
        <label>Name</label>
        <input name="name" ref={register} />
        <label>Address</label>
        <input name="address" ref={register} />
        <label>Date</label>
        <input name="date" ref={register} />
        <label>Order Number</label>
        <input name="order" ref={register} />
        <input type="submit" />
      </form>

       
       
      </main>
    </>
  )
}
