import Head from "next/head";
import { auth, provider } from "../firebase/firebase";
import { signInWithPopup } from "firebase/auth";
import { useRouter } from 'next/navigation';

export default function SignIn() {
  const router = useRouter();
  const loginWithGoogle = () => {
    signInWithPopup(auth, provider).then((results) => {
      console.log(results);
      console.log(results.user.displayName)
      localStorage.setItem("isAuth", true);
      router.push("/home")
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={loginWithGoogle}>Googleアカウントでログイン</button>
        <></>
      </main>
    </>
  );
}
