import Head from "next/head";
import { auth, provider } from "../firebase/firebase";
import { signInWithEmailAndPassword, signInWithPopup } from "firebase/auth";
import { useRouter } from "next/navigation";
import { useAuthContext } from "components/context/state";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function SignIn() {
  const { isAuth, setIsAuth } = useAuthContext();
  const [ email, setEmail ] = useState("");
  const [ password, setPassword ] = useState("");
  const router = useRouter();
  const loginWithGoogle = () => {
    signInWithPopup(auth, provider).then((results) => {
      setIsAuth(true);
      localStorage.setItem("isAuth", true);
      router.push("/home");
    });
  };
  const loginWithEmail = () => {
    signInWithEmailAndPassword(auth, email, password).then((userCredential) => {
      const user = userCredential.user;
      console.log(user);
    });
  };

  const changeEmail = (e) => {
    setEmail(e.target.value);
  };

  const changePassword = (e) => {
    setPassword(e.target.value);
  };

  useEffect(() => {
    if (isAuth) {
      console.log(isAuth);
      router.push("/home");
    }
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input
          type="text"
          placeholder="メールアドレスを入力"
          onChange={changeEmail}
        />
        <input
          type="text"
          placeholder="パスワードを入力"
          onChange={changePassword}
        />
        <button onClick={loginWithEmail}>ログイン</button>
        <button onClick={loginWithGoogle}>Googleアカウントでログイン</button>
        <Link href="/signup">アカウント新規登録はこちら</Link>
        <></>
      </main>
    </>
  );
}
